version: "3.7"

services:
  react:
      build: .
      ports:
        - "3000:3000"
  json-server:
      image: clue/json-server
      ports:
        - "80:80"
      volumes:
        - ./db.json:/data/db.json
      
      