import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'
import NavBar from '../components/NavBar'
import CardChakra from '../components/CardChakra'
import FooterChakra from '../components/FooterChakra'
import { api } from '../services/api';

export default function Index() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <div className="container min-vh-100">
          <h1>Bem Vindo ao Beneficios Moura</h1>
        </div>
        <FooterChakra />
      </main>
    </>
  )
}