import { useEffect, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Spinner, Flex } from "@chakra-ui/react";

import { api } from "../../services/api";
import { IBeneficio } from "../../dtos/IBeneficio";
import { CardBeneficio } from "../../components/cardBeneficioBeneficios";
import NavBar from "../../components/NavBar";

export default function Beneficio() {
  const { query, isReady } = useRouter();
  const [beneficio, setBeneficio] = useState<IBeneficio>();

  async function getBeneficio() {
    try {
      const response = await api.get(`/beneficios/${query.id}`);
      setBeneficio(response.data);
    } catch (error) {
      console.log(error);
    }
  }

  useEffect(() => {
    if (isReady) {
      getBeneficio();
    }
  }, [isReady]);

  return (
    <>
      <Head>
        <title>Benefício</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container min-vh-100">
          {beneficio ? (
            <CardBeneficio
              title={String(beneficio?.title)}
              description={String(beneficio?.description)}
              id={Number(beneficio?.id)}
            />
          ) : (
            <Flex justifyContent={"center"} alignItems={"center"} minH={"container.md"}>
              <Spinner
                thickness="4px"
                speed="0.65s"
                emptyColor="gray.200"
                color="blue.500"
                size="xl"
              />
            </Flex>
          )}
        </div>
      </main>
    </>
  );
}

//renderização condicional react
